
services:
  rng:
    build: ./rng
    deploy:
      replicas: 3


  hasher:
    build: ./hasher
    deploy:
      replicas: 3


  webui:
    build: ./webui
    ports:
    - "8000:80"
    volumes:
    - "./webui/files/:/files/"

  redis:
    image: redis

  worker:
    build: ./worker
    deploy:
      replicas: 6

